services:
  main:
    image: main:latest
    container_name: main
    build:
      context: ./docker-pump-fun-main
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/pumpfun
    depends_on:
      - mongodb
    networks:
      - pump-network
    volumes:
      - ./scraper-output:/usr/src/app/output # Map the local directory to the container's output folder

  include:
  - ./docker-pump-fun-solscal-fetcher/docker-compose.yaml 

  data-cleaner:
    image: pump-fun-data-cleaner:latest
    container_name: data-cleaner
    restart: always
    build:
      context: ./docker-pump-fun-data-cleaner
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    networks:
      - pump-network

  sentiment-analyser:
    image: pump-fun-sentiment-analyser:latest
    container_name: sentiment-analyser
    restart: always
    build:
      context: ./docker-pump-fun-sentiment-analyser
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks: 
      - pump-network

  token-search:
    image: pump-fun-token-search:latest
    container_name: token-search
    restart: always
    build:
      context: ./docker-pump-fun-token-search
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - pump-network

  fetch-replies:
    image: pump-fun-reply-fetcher:latest
    container_name: fetch-replies
    restart: always
    build:
      context: ./docker-pump-fun-reply-fetcher
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - pump-network
   
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - pump-network
    volumes:
      - ./data/mongodb:/data/db
networks:
  pump-network:
    driver: bridge