version: "3.9"

services:
  scraper:
    image: pump-fun-scraper:latest
    build:
      context: ./docker-pump-fun-scraper # The current directory where the Dockerfile is located
      dockerfile: Dockerfile
    #environment:
    #  - S3_BUCKET_NAME=your-bucket-name # Replace with your S3 bucket name
    #  - AWS_ACCESS_KEY_ID=your-access-key-id # Replace with your AWS Access Key
    #  - AWS_SECRET_ACCESS_KEY=your-secret-access-key # Replace with your AWS Secret Key
    #  - AWS_REGION=us-east-1 # Replace with your AWS Region
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./scraper-output:/usr/src/app/output # Map the local directory to the container's output folder
    networks:
      - pump-network
  fetch-replies:
    image: pump-fun-reply-fetcher:latest
    build:
      context: ./docker-pump-fun-reply-fetcher
      dockerfile: Dockerfile
    volumes:
      - ./fetcher-output:/usr/src/app/output
    networks:
      - pump-network
    ports:
      - "3000:3000" # Expose the API fetcher on port 3000 for debugging

networks:
  pump-network:
    driver: bridge