version: "3.9"

services:
  scraper:
    image: pump-fun-scraper:latest
    container_name: scraper
    build:
      context: ./docker-pump-fun-scraper # The current directory where the Dockerfile is located
      dockerfile: Dockerfile
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./scraper-output:/usr/src/app/output # Map the local directory to the container's output folder
    networks:
      - pump-network
  fetch-replies:
    image: pump-fun-reply-fetcher:latest
    container_name: fetch_replies
    build:
      context: ./docker-pump-fun-reply-fetcher
      dockerfile: Dockerfile
    volumes:
      - ./fetcher-output:/usr/src/app/output
    networks:
      - pump-network
    ports:
      - "3000:3000" # Expose the API fetcher on port 3000 for debugging

networks:
  pump-network:
    driver: bridge