services:
  solscan-fetcher:
    env_file: ".env"
    image: pump-fun-solscan-fetcher:latest
    container_name: solscan-fetcher
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    networks:
      - pump-network
networks:
  pump-network:
    driver: bridge