services:
  pumpfun-analyser-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pumpfun-analyser-server
    ports:
      - "3010:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"